### ISSUE TITLE
how to generate {city}_checkin_with_active_regionId.csv

### ISSUE THREAD

**Issue by Perseus1993** [Wonderdch/CLSPRec#1]
Thanks for the code !
But how can I get  {city}_checkin_with_active_regionId.csv
from origin data "Participatory Cultural Mapping Based on Collective Behavior Data in Location Based Social Networks?"

**Comment by Wonderdch** [comment]
{city}_checkin_with_active_regionId.csv is the source data, collect from Foursquare by [Dingqi Yang](https://sites.google.com/site/yangdingqi/home/foursquare-dataset).

You can only run data_preprocessor.py to generate train/test data from {city}_checkin_with_active_regionId.csv

**Comment by kevin-xuan** [comment]
Hello, I find two most revelant data source: 3. Global-scale Check-in Dataset and 5. Global-scale Check-in Dataset with User Social Networks, and the specific information are as follows:
<img width="1133" alt="截屏2024-08-01 11 49 35" src="https://github.com/user-attachments/assets/9dc01299-f83a-402d-9f7f-2ea3f3670848">
<img width="663" alt="截屏2024-08-01 11 52 20" src="https://github.com/user-attachments/assets/ebba060b-c529-4ce7-b45a-057fd35a1d45">
The contained files end with ".txt" insteaf of ".csv". If I want to apply this method on new datasets, how can I get {city}_checkin_with_active_regionId.csv?

**Comment by Wonderdch** [comment]
> Hello, I find two most revelant data source: 3. Global-scale Check-in Dataset and 5. Global-scale Check-in Dataset with User Social Networks, and the specific information are as follows: <img alt="截屏2024-08-01 11 49 35" width="1133" src="https://private-user-images.githubusercontent.com/87954969/354071673-9dc01299-f83a-402d-9f7f-2ea3f3670848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDMyMTAsIm5iZiI6MTcyMjUwMjkxMCwicGF0aCI6Ii84Nzk1NDk2OS8zNTQwNzE2NzMtOWRjMDEyOTktZjgzYS00MDJkLTlmN2YtMmVhM2YzNjcwODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZDY4Njc2NzZiMmRhMmM5MmEzMTU2NzUxODcwYmIzYzFhMWU3YWNhZWZlOTEzZmE3YTdjOTQ2YjUyMzM4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUK8cfCsyzJFF5f1ELMeZUdFDOKfk9Jp_3HZCIl1P4Q"> <img alt="截屏2024-08-01 11 52 20" width="663" src="https://private-user-images.githubusercontent.com/87954969/354071748-ebba060b-c529-4ce7-b45a-057fd35a1d45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDMyMTAsIm5iZiI6MTcyMjUwMjkxMCwicGF0aCI6Ii84Nzk1NDk2OS8zNTQwNzE3NDgtZWJiYTA2MGItYzUyOS00Y2U3LWI0NWEtMDU3ZmQzNWExZDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTIxZmMzOGU5Yjc2NjVmZmE0ODhkYmEwNDI2MTU4OGZmZjgyMWYzMDJmZjVkNzc4YjQyZTRjMTk5YWY0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uDKkhJIchMz6IWVuVpH2CPMptK-AysIoPXKKB0nF6K8"> The contained files end with ".txt" insteaf of ".csv". If I want to apply this method on new datasets, how can I get {city}_checkin_with_active_regionId.csv?

For more information about data generation you can refer to CFPRec's [GitHub](https://github.com/tt2615/CFPRec?tab=readme-ov-file#raw-data) and the paper's chapter "4.1 Experimental Setup".

**Comment by kevin-xuan** [comment]
Thanks
